language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install . --use-mirrors
# command to run tests
script: nosetests --with-spec
